spring:
  datasource:
    url: jdbc:mysql://localhost:3306/devblog
    #jdbc????? ????jdbc:mysql://????????:??/????
    username: devblog
    #?????
    password: nNjbLAzZFp3JFFCC
    #?????
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  servlet:
    session:
      timeout: 1s