spring:
  datasource:
    url: jdbc:mysql://localhost:3306/devblog
    #jdbc????? ????jdbc:mysql://????????:??/????
    username: root
    #?????
    password: bE2fplx9TGGWdhlM
    #?????
    driver-class-name: com.mysql.cj.jdbc.Driver